version: '3'

services:
  dbPostgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studentsCalendar
    ports:
      - "4040:5432"
    restart: always

  adminer:
    image: adminer
    ports:
      - "4242:8080"
    restart: always
