version: '3'

services:
  dbPostgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studentsCalendar
    ports:
      - "4040:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
